### PR TITLE
patch npcs not working and correct the height of the Roblox player

### PR DESCRIPTION
**Pull request by IzeWare**
Idk if this was only my issue or a global issue
I'm using this citizens version: https://ci.citizensnpcs.co/job/citizens2/3641/
and i edited the default port to be on the IP in ReplicatedStorage

### CODE REVIEW

**Comment by IzeWare** [comment]
i'll close this for now its not working as expected

**Comment by IzeWare** [comment]
Works now but might be unstable

**Review by Atmerek — CHANGES_REQUESTED** [review]
What's the `.name` file? I'd like it deleted if not needed.

**Comment by IzeWare** [comment]
> What's the `.name` file? I'd like it deleted if not needed.

oh, sorry that was me compiling it

**Pull request merged**
